In [ ]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [ ]:
# Imports
import numpy as np
import random

> This notebook will talk about several ways of generating random numbers using several Python libraries such as random, numpy, etc.
We will also talk a bit about how seeds work and why they are important when doing data science projects!

## Using the `random` module

The pseudo-random number generator function random(), which generates a random float number between 0.0 and 1.0, is used by functions in the random module. Many games, lotteries, and other applications needing random number creation use this specific type of function.

In [ ]:
num = random.random()
num

0.9828052927616455

In [ ]:
# Selecting a random entry from a given list
l1 = [1,2,3,'turtle',5.3]
random.choice(l1)

1

In [ ]:
# Selecting a random character from a string
s = "CMPUT 200"
random.choice(s)

'M'

In [ ]:
# Generating random number lists based in a given range and step size
random.randrange(20, 50, 3)

23

In [ ]:
# Generating random numbers using a seed value
# A seed value helps to reproduce experiments whenever someone else tries to run them and helps less deviation in the results
random.seed(7)
random.random()

0.32383276483316237

In [ ]:
# Shuffling lists in Python
random.shuffle(l1)
l1

[1, 3, 5.3, 'turtle', 2]

In [ ]:
# Generating random numbers using a uniform distribution in a specific range
print(random.uniform(5, 10))

5.362181433337714


## Using `numpy` for random numbers

In [ ]:
# Generating a list of random numbers using numpy
np.random.seed(42)
np.random.random(size=5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [ ]:
# How do we use this for our applications?
# Let's simulate an example of 100 coin flips where getting a random number <0.5 counts as heads
# Here we'll try to count the number of heads
heads = np.random.random(size = 100) < 0.5
print(f"The array with heads or not is represented as:\n{heads}")
n_heads = np.sum(heads)
print(f"\nThe number of heads generated is: {n_heads}")

The array with heads or not is represented as:
[ True  True False  True  True False False False  True False  True  True
 False False False False False  True  True  True  True False  True False
 False False False False  True  True False  True  True False  True False
 False False  True  True False  True False False False  True  True False
  True  True False False False False  True False False  True False False
 False False False  True  True False False False False False False False
 False False False False  True  True  True False  True  True False  True
 False  True  True False  True  True False False  True False  True  True
 False False False False]

The number of heads generated is: 41


In [ ]:
# Using the new default_rng module in numpy
# The default_rng is a module which you can generate with a specific seed to improve reproducibility of your experiments
rng = np.random.default_rng(seed = 42)
print(rng)

Generator(PCG64)


>PCG64 is the 128-bit implementation of O’Neill’s permutation congruential generator (https://www.pcg-random.org/)

In [ ]:
# Generating random floats using our number generator now
rng = np.random.default_rng(seed = 42)
rng.random()

0.7739560485559633

In [ ]:
# Generating random integers given a range
rng = np.random.default_rng(seed = 42)
rng.integers(low=40, high=50, size=6)

array([40, 47, 46, 44, 44, 48])

In [ ]:
# Creating n-dimensional integer arrays using the same function
rng = np.random.default_rng(seed = 42)
rng.integers(low=40, high=50, size= (6,6))

array([[40, 47, 46, 44, 44, 48],
       [40, 46, 42, 40, 45, 49],
       [47, 47, 47, 47, 45, 41],
       [48, 44, 45, 43, 41, 49],
       [47, 46, 44, 48, 45, 44],
       [44, 42, 40, 45, 48, 40]])

In [ ]:
# Since we have the seed specified the random generation is easy
rng = np.random.default_rng(seed=42)
arr1 = rng.random((3, 3))
arr1

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])